import catalog from "./data/work-catalog.json";
import { continueWithGoogle, ensureAnonymousSession, getSupabase, session } from "./discussion/supabase.js";
import { toggleBookmark } from "./discussion/service.js";
import { TagPreferences } from "./preferences.js";

const pageSize = 24;
const byParent = new Map(Object.entries(catalog.by_parent_work_id || {}));
const knownTags = catalog.tags || [];
const el = (tag, className, text) => { const node = document.createElement(tag); if (className) node.className = className; if (text != null) node.textContent = text; return node; };
const safeIdentity = user => user?.is_anonymous ? "Anonymous reader" : (user?.user_metadata?.full_name || user?.user_metadata?.name || "Linked reader");

async function signOut() { const db = await getSupabase(); await db?.auth.signOut(); TagPreferences.clear(); }
function nav(active) { const n = el("nav", "account-tabs"); for (const [href,label] of [["/account","Profile"],["/account/bookmarks","Bookmarks"],["/account/settings","Settings"]]) { const a=el("a", active===href?"is-active":"", label); a.href=href; a.addEventListener("click", e=>{e.preventDefault(); history.pushState({},"",href); Account.render();}); n.append(a);} return n; }
async function authBox(root) { const s = await session().catch(()=>null); const box=el("section","account-card"); const h=el("h2",null,"Private account"); const p=el("p",null,s?`Signed in as ${safeIdentity(s.user)}.`:"You are signed out."); box.append(h,p); const row=el("div","account-actions"); if (!s) { const anon=el("button",null,"Continue anonymously"); anon.onclick=async()=>{await ensureAnonymousSession(); Account.render();}; row.append(anon); } const google=el("button",null,s?.user?.is_anonymous?"Link Google account":"Continue with Google"); google.onclick=()=>continueWithGoogle(); row.append(google); if (s) { const out=el("button",null,"Sign out"); out.onclick=async()=>{await signOut(); Account.render();}; row.append(out); } box.append(row); root.append(box); return s; }
function shell(root,title,active){ document.body.classList.remove("reader-active"); root.replaceChildren(); const wrap=el("main","account-root"); const h=el("h1",null,title); wrap.append(h,nav(active)); root.append(wrap); return wrap; }
async function profile(root){ const wrap=shell(root,"Account","/account"); const s=await authBox(wrap); const info=el("section","account-card"); info.append(el("h2",null,"Status"), el("p",null,s?`Account type: ${s.user?.is_anonymous?"anonymous recovery identity":"Google-linked identity"}`:"Bookmarks and settings are private after sign-in.")); wrap.append(info); }
async function bookmarks(root){ const wrap=shell(root,"Bookmarks","/account/bookmarks"); const s=await authBox(wrap); const list=el("section","account-card"); list.append(el("h2",null,"Saved works")); wrap.append(list); if(!s){list.append(el("p",null,"Sign in to see bookmarks.")); return;} const status=el("p",null,"Loading bookmarks…"); list.append(status); const db=await getSupabase(); const {data,error}=await db.from("bookmarks").select("work_id,created_at").order("created_at",{ascending:false}).limit(pageSize); if(error){status.textContent="Bookmarks are unavailable offline. Please retry."; const b=el("button",null,"Retry"); b.onclick=()=>bookmarks(root); list.append(b); return;} list.removeChild(status); if(!data?.length){list.append(el("p",null,"No bookmarks yet.")); return;} const grid=el("div","bookmark-grid"); for(const row of data){ const work=byParent.get(String(row.work_id)); const card=el("article","bookmark-card"); if(work?.thumb){ const img=new Image(); img.src=work.thumb; img.alt=""; img.loading="lazy"; card.append(img);} card.append(el("h3",null,work?.display || `Missing work ${row.work_id}`)); const tags=el("div","tag-list"); (work?.tags||[]).forEach(t=>tags.append(el("span","tag-chip",t))); card.append(tags); if(work?.slug){ const a=el("a",null,"Read"); a.href=`/?source=${encodeURIComponent(work.source||"e")}&work=${encodeURIComponent(work.slug)}&chapter=${encodeURIComponent(work.chapters?.[0]||"chapter_1")}`; card.append(a);} const rm=el("button",null,"Remove"); rm.onclick=async()=>{ await toggleBookmark(String(row.work_id), true); card.remove();}; card.append(rm); grid.append(card);} list.append(grid); }
async function settings(root){ const wrap=shell(root,"Settings","/account/settings"); const s=await authBox(wrap); const panel=el("section","account-card"); panel.append(el("h2",null,"Tag preferences")); wrap.append(panel); if(!s){panel.append(el("p",null,"Sign in to save personal tag preferences.")); return;} const snap=await TagPreferences.loadForCurrentUser().catch(()=>TagPreferences.snapshot()); const q=el("input"); q.type="search"; q.placeholder="Search known tags"; const status=el("p","settings-status", knownTags.length?"":"No structured tags are present in the catalog yet. Add authoritative tags through the generation pipeline before filtering is complete."); const list=el("div","tag-settings-list"); const selected=new Set(snap.personalExcluded); const allowed=new Set(snap.allowedDefaults); const draw=()=>{list.replaceChildren(); const query=TagPreferences.normalizeTag(q.value); knownTags.filter(t=>!query||t.includes(query)).slice(0,100).forEach(t=>{const label=el("label","tag-option"); const cb=document.createElement("input"); cb.type="checkbox"; cb.checked=selected.has(t); cb.onchange=()=>cb.checked?selected.add(t):selected.delete(t); label.append(cb, document.createTextNode(` ${t}`)); list.append(label);});}; q.oninput=draw; const save=el("button",null,"Save preferences"); save.onclick=async()=>{status.textContent="Saving…"; try{await TagPreferences.save({personalExcluded:[...selected],allowedDefaults:[...allowed]}); status.textContent="Saved.";}catch(e){console.warn(e); status.textContent="Could not save. Check connection and retry.";}}; const restore=el("button",null,"Restore defaults"); restore.onclick=async()=>{selected.clear(); allowed.clear(); await TagPreferences.save({personalExcluded:[],allowedDefaults:[]}); draw(); status.textContent="Defaults restored.";}; panel.append(q,list,save,restore,status); draw(); }
export class Account { static async render(){ const root=document.getElementById("reader-container"); const path=location.pathname; if(path.endsWith("/bookmarks")) return bookmarks(root); if(path.endsWith("/settings")) return settings(root); return profile(root);} }
